import type { components } from '@/api/generated/schema'

export type DogListItem = components['schemas']['DogListItemApiDto']
export type DogDetails = components['schemas']['DogDetailsApiDto']
export type DogPage = components['schemas']['DogListItemApiDtoApiPagedResult']
export type ShelterListItem = components['schemas']['ShelterListItemApiDto']
export type ShelterPage = components['schemas']['ShelterListItemApiDtoApiPagedResult']
export type UserSession = components['schemas']['AdopterPortalUserApiDto']
export type LoginRequest = components['schemas']['AdopterPortalLoginRequest']
export type SavedSearch = components['schemas']['SavedDogSearchDto']
export type SavedSearchDetails = components['schemas']['SavedDogSearchDetailsDto']
export type SavedSearchCreate = components['schemas']['SavedDogSearchCreateRequest']
export type Application = components['schemas']['AdoptionApplicationApiDto']
export type ApplicationPage = components['schemas']['AdoptionApplicationApiDtoApiPagedResult']
export type CreateApplication = components['schemas']['CreateAdoptionApplicationApiRequest']
export type NotificationCenter = components['schemas']['NotificationCenterResultDto']
export type NotificationItem = components['schemas']['NotificationCenterItemDto']
export type NotificationPreference = components['schemas']['NotificationPreferenceApiDto']
export type UpdateNotificationPreference = components['schemas']['UpdateNotificationPreferenceApiRequest']
export type AdopterProfile = components['schemas']['AdopterProfileApiDto']
export type UpdateAdopterProfile = components['schemas']['UpdateAdopterProfileApiRequest']
export type CopilotResponse = components['schemas']['AdoptionCopilotResponseApiDto']
export type InsightPage = components['schemas']['OperationalInsightDtoPagedResult']
export type Insight = components['schemas']['OperationalInsightDto']
